Added Traackr.com
matomo-org/device-detector pull request #5584
Opened 2017-02-10 11:30 UTC by shaeney

HI, I am not really familiar with Git or php, being a .Net developer who uses TFS.

But I'd like to contribute

2017-02-10 12:48 UTC, Findus23 commented
@shaeney Could you add tests in `Tests/fixtures/bots.yml` for the new bots? (Similar to https://github.com/piwik/device-detector/commit/c219415c2ad114874adb77ad6753d1663710c6b7)

2017-02-15 13:24 UTC, shaeney commented
Can anyone help? I am not familiar with open source/git, so dont know how to find out what I need to do to fix this?

2017-02-15 14:27 UTC, Findus23 commented
@shaeney The error travis is reporting (https://travis-ci.org/piwik/device-detector/jobs/201858723#L367) is that in https://github.com/piwik/device-detector/pull/5584/files#diff-658652a1b8930dae0035e1dee2883900R1390 you set the url of the bot to an empty string but in `Tests/fixtures/bots.yml` you are missing the `url` key. 
Best solution is to add an url (http://feeltiptop.com) to both of them.

In addition you'll need a similar test for Traackr.com and WebClient.
And it would be nice to add more information to WebClient if you have any. (Or just add it with the name "Generic Bot" if there are none)

2017-02-15 15:21 UTC, shaeney commented
@Findus23 Can you give me a hand? While I am familiar with TDD in a .Net world, I dont really understand whats expected of me here. I've tried to reverse engineer what I need to do, but cant work it out?

I thought Id need to add text to
Tests\fixtures\bots.yml for example

- 
  user_agent: Traackr.com
  bot:
    name: Traackr.com
    category: Crawler
    url: http://www.traackr.com

and this would be matched by the equivalent in the regex bots.yml?

But I cant interpret what the error log is telling me?

2017-02-15 15:33 UTC, Findus23 commented
@shaeney The last commit is looking good. Are you sure that the complete user agent is `Traackr.com`? 
For the key `user_agent` in the test you need an example of the user agent.

2017-02-15 15:42 UTC, Findus23 requested changes
I hope this helps

2017-02-15 15:42 UTC, Findus23 commented on Tests/fixtures/bots.yml
> +  user_agent: Traackr.com
This test is not needed any more as the second one is working

2017-02-15 15:42 UTC, Findus23 commented on regexes/bots.yml
> +  url: ''
Could you add the url here instead of an empty string?

2017-02-15 15:42 UTC, Findus23 commented on Tests/fixtures/bots.yml
> +    category: Crawler
You need to add the url here

2017-02-15 15:42 UTC, Findus23 commented on regexes/bots.yml
> +  name: 'WebClient'
You need to change the name to 'Generic Bot' to match the test.

2017-03-09 17:42 UTC, sgiehl commented on regexes/bots.yml
> +  name: 'Generic Bot'
Guess this block moved in while merging. It shouldn't be present in that file anymore, so please remove it as well.

2018-05-04 10:05 UTC, sgiehl commented
Closing stalled pull request

2018-05-04 10:05 UTC, closed without merging