PR device3
matomo-org/device-detector pull request #5629
Opened 2017-06-09 10:12 UTC by sanchezzzhak

2017-06-23 13:39 UTC, sanchezzzhak commented
can merge?

2017-06-30 19:38 UTC, sgiehl requested changes
Left a few comments for improvements. Will merge after applied

2017-06-30 19:38 UTC, sgiehl commented on regexes/device/mobiles.yml
> +  device: 'smartphone'
If I see that right all devices from 4Good start with `4Good`, so maybe we could make that detection more generic like:
```
regex: '4Good|S450m [43]G|S555m 4G|S501m 3G|T700i_3G|Light A103'
```

And add a generic model detection below:
```
- regex: '4Good[ _]([^;/]+) Build'
  model: '$1'
- regex: '4Good[ _]([^);/ ]+)'
  model: '$1'
```

2017-06-30 19:38 UTC, sgiehl commented on regexes/device/mobiles.yml
> +  regex: 'Bravis|A501 Bright|NB(?:10[56]|7[145])|NP101'
There's also a model NB751, maybe you could add that as well.

2017-06-30 19:38 UTC, sgiehl commented on regexes/device/mobiles.yml
> +    - regex: 'LS-4004'
Could you also add `LS-5505` (Water F1) ?

2017-06-30 19:38 UTC, sgiehl commented on regexes/device/mobiles.yml
> +      model: 'Stratus 4'
Could you additionally add `FS403` (Cumulus 1) and `FS401` (Stratus 1)

2017-07-02 12:54 UTC, Findus23 commented
Hi, I have added the necessary icons: https://github.com/piwik/piwik-icons/commit/9db9942f352ab729f4a31642f30c7d95dcdd8824

2017-07-02 22:00 UTC, sanchezzzhak commented on regexes/device/mobiles.yml
> +    - regex: 'LS-4004'
Added

2017-07-02 22:00 UTC, sanchezzzhak commented on regexes/device/mobiles.yml
> +      model: 'Stratus 4'
Added

2017-07-02 22:10 UTC, sanchezzzhak commented on regexes/device/mobiles.yml
> +  regex: 'Bravis|A501 Bright|NB(?:10[56]|7[145])|NP101'
Added

2017-07-02 22:25 UTC, sanchezzzhak commented on regexes/device/mobiles.yml
> +  device: 'smartphone'
Added

2017-07-03 06:10 UTC, sgiehl commented
Thanks for the changes :+1:

2017-07-03 06:10 UTC, sgiehl approved these changes

2017-07-03 06:10 UTC, merged