Add Pecl YAML parser
matomo-org/device-detector pull request #5876
Opened 2018-11-29 11:43 UTC by mallsbill

2018-11-29 11:53 UTC, mimmi20 commented
@mallsbill Please add some information about this optional dependency in the composer.json.

2018-11-29 13:35 UTC, mallsbill commented
> @mallsbill Please add some information about this optional dependency in the composer.json.

@mimmi20 I added ext-yaml to suggest

Last travis job failed on "composer require doctrine/cache ~1.2" on PHP 5.3 build
But it should work if you re-run it

2018-12-01 22:14 UTC, sgiehl requested changes
Left some comments, otherwise looks good :+1:

2018-12-01 22:14 UTC, sgiehl commented on Yaml/Pecl.php
> +class Pecl implements Parser
Would you mind adding a docblock for the class describing the purpose?

2018-12-01 22:14 UTC, sgiehl commented on Yaml/Pecl.php
> +            throw new \Exception('Pecl YAML extension is not installed');
please add brackets even for one line if statements.

2018-12-06 22:03 UTC, sgiehl approved these changes

2018-12-06 22:03 UTC, merged