Added Beaker Browser
matomo-org/device-detector pull request #5894
Opened 2019-01-27 03:32 UTC by da2x

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
like Gecko) BeakerBrowser/0.8.2 Chrome/66.0.3359.181 Electron/3.0.9
Safari/537.36

https://beakerbrowser.com/

2019-02-01 11:57 UTC, sgiehl requested changes
Would you maybe also add a test for the new Browser?

2019-02-01 11:57 UTC, sgiehl commented on regexes/client/browsers.yml
> +- regex: 'Beaker ?Browser(?:[/ ](\d+[\.\d]+))?''
There is one `'` to much at the end

2019-02-02 18:14 UTC, da2x commented
Fixed mistakes, resolved conflicts, and added a test.

2019-02-04 17:33 UTC, sgiehl approved these changes

2019-02-04 17:35 UTC, merged