[wip] add new browsers, apps and devices
matomo-org/device-detector pull request #6011
Opened 2019-08-15 08:17 UTC by mimmi20

2019-08-15 09:04 UTC, sgiehl commented
I see what you are trying to do with adding new tests. Could you maybe move adding your new fixtures after the already existing fixtures have been sorted? That way they will simply be added at the end and it's easier to see the actual changes and it won't conflict with other PRs that much.

Also I'm not sure why the surrounding `"` from the version numbers have been removed everywhere.
That actually doesn't hurt for the PHP tests here, but some of the ports to other languages are using the test fixtures here, and they have a problem as they are "detected" as invalid numbers without those surrounding `"`
Guess the script to add those chars didn't work on your system:
https://github.com/matomo-org/device-detector/blob/6bb8507bd06f041b073924368f18f0b7f74b7402/misc/sortTestFixtureFiles.php#L116

2019-08-15 12:18 UTC, mimmi20 commented
@sgiehl The PR is not finished yet. I work on a windows system, and `sed` doesn't work there. This will be fixed tomorrow. I used the `misc/sortTestFixtureFiles.php` file to rewrite and add the test cases.

2019-08-16 14:23 UTC, mimmi20 commented
@sgiehl You may review now.

2019-08-16 14:33 UTC, Findus23 requested changes
I can't say much about the non-browser changes, but I am not sure if spliting up iOS/mobile browser variants is that useful. After all DeviceDetector is already able to keep them apart via the OS detection.

2019-08-16 14:33 UTC, Findus23 commented on Parser/Client/Browser.php
> +        'DA' => 'Dalvik',
Dalvik isn't a browser, but something android webviews sometimes send as a useragent:
https://stackoverflow.com/questions/23804278/browser-sending-dalvik-as-user-agent

2019-08-18 15:28 UTC, mimmi20 commented
I will split the PR.

2019-08-18 15:28 UTC, closed without merging