Adds detection for multiple notebooks
matomo-org/device-detector pull request #6292
Opened 2020-05-05 19:52 UTC by liviuconcioiu

2020-05-05 20:59 UTC, mimmi20 requested changes

2020-05-05 20:59 UTC, mimmi20 commented on misc/statistics.php
> +    format($deviceTypes[10], $parsedUAs), getPercentage($deviceTypes[13], $parsedUAs),
Should this not be `format($deviceTypes[13], $parsedUAs), getPercentage($deviceTypes[13], $parsedUAs)`

2020-05-06 08:26 UTC, sgiehl commented
@liviuconcioiu  I'm not sure if we should add a new device type notebook 🤔  Nowadays most people are using notebooks, but most of the can't be detected as such and will be shown as desktop. Starting to detect some of them as notebooks now (and only those using facebook), might give a wrong insight

2020-05-06 08:46 UTC, liviuconcioiu commented
I see. I will move them to desktop then.

2020-08-11 20:11 UTC, sgiehl commented
@liviuconcioiu I'll merge this to a local branch an recreate the PR with the required changes...

2020-08-11 20:11 UTC, merged