create parser AliasDevice  get model raw name from useragent
matomo-org/device-detector pull request #6296
Opened 2020-05-12 12:22 UTC by sanchezzzhak

issue #6267

2020-10-27 10:43 UTC, sanchezzzhak commented
@sgiehl is there a ready setup PHPCS for phpstorm 2020.3 ?

2020-10-27 10:48 UTC, sgiehl commented
if you installed the composer dependencies there should be one in `vendor\bin\phpcs` (and `vendor\bin\phpcbf` for automatic fixes)

2020-12-11 12:25 UTC, mimmi20 requested changes

2020-12-11 12:25 UTC, mimmi20 commented on Tests/Parser/fixtures/alias_devices.yml
> + user_agent: Mozilla/5.0 (Android 7.0; samsung SM-A710F) AppleWebKit/537.36 KHTML, like Gecko Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 SurfBrowser/3.0
Please fix indentation

2020-12-11 12:25 UTC, mimmi20 commented on Tests/Parser/AliasDeviceTest.php
> +        $this->assertEquals(null, $result);
Please use `$this->assertNull($result)`

2020-12-11 14:59 UTC, mimmi20 approved these changes, later dismissed

2021-06-14 17:00 UTC, sanchezzzhak commented
I found a good use for AliasDevice, I will try to pass the changes from https://github.com/sanchezzzhak/node-device-detector/tree/pr_device_info8 in PHP

My 22k tests were reduced from 2 minutes to 43 seconds, without cache

2021-06-15 08:30 UTC, sanchezzzhak commented
summary

Added new methods to device parsers
public list:
AbstractDeviceParser::setBrandIndexes(array brands)  - parsing only selected brands
AbstractDeviceParser::parseAllMatch()    - same as parse, only returns all matches
some checks in the code have been moved as helper methods
AbstractDeviceParser::hasBrand(string brand)
AbstractDeviceParser::hasDeviceType(string deviceType)
private list:
parseResult(bool all = false) - this method implements new scanning logic
parseForBrand
shouldExistBrandOrException

Without indexing, tests are performed for 43 seconds, with 20 seconds.

Where can this be useful?
Mainly in long-lived processes, realtime services, background tasks, testing

2021-11-22 12:39 UTC, sanchezzzhak commented
Rejected - this function is not needed yet.
Since there is memcache.

**I don't delete the branch in case it comes in handy.**

In Node Js, this thing works fine.

2021-11-22 12:39 UTC, closed without merging