Added a few Android devices
matomo-org/device-detector pull request #6371
Opened 2020-09-22 14:38 UTC by GregOriol

2020-09-22 16:36 UTC, sanchezzzhak commented
I have a couple additional "Infinix" useragents

* model  **Smart 4 or  (S4)**
* Mozilla/5.0 (Linux; Android 9; Infinix X653) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36

* model  **Note 7 (phablet)**
* Mozilla/5.0 (Linux; U; Android 10; fr-fr; Infinix X690 Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36

* model **Hot 7**
* Mozilla/5.0 (Linux; Android 8.1.0; Infinix X624) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Mobile Safari/537.36

Can we add it to this PR?

2020-09-23 07:16 UTC, GregOriol commented
@sanchezzzhak Done!

2020-09-23 08:04 UTC, sanchezzzhak requested changes

2020-09-23 08:08 UTC, GregOriol commented
@sanchezzzhak Done!

2020-09-23 08:12 UTC, sanchezzzhak approved these changes

2020-09-26 22:03 UTC, merged