Adds detection for NFS Browser
matomo-org/device-detector pull request #6481
Opened 2020-12-03 17:22 UTC by liviuconcioiu

2020-12-03 17:50 UTC, sanchezzzhak requested changes

2020-12-03 17:50 UTC, sanchezzzhak commented on regexes/client/browsers.yml
> +  version: '$1'
add
```yml
engine:
    default: 'Blink'
```

2020-12-04 08:35 UTC, sanchezzzhak approved these changes, later dismissed

2020-12-04 09:09 UTC, sgiehl approved these changes

2020-12-04 09:09 UTC, merged