Adds detection for bots
matomo-org/device-detector pull request #6498
Opened 2020-12-06 16:42 UTC by liviuconcioiu

2020-12-07 06:12 UTC, sanchezzzhak requested changes

2020-12-07 06:12 UTC, sanchezzzhak commented on regexes/bots.yml
> +- regex: 'BW'
2 characters is very small, you need to add one more condition to avoid collisions in the future.
e.g.
```yml
BM/(?:(\d+[\.\d]+))
```

2020-12-15 10:11 UTC, sgiehl commented
@sanchezzzhak  guess that one looks good to merge now, right?

2020-12-15 10:25 UTC, sanchezzzhak approved these changes

2020-12-15 10:27 UTC, sanchezzzhak commented
> @sanchezzzhak guess that one looks good to merge now, right?

Yes, it can be merged into the master, I just checked

2020-12-15 10:30 UTC, merged