Improves macOS and iOS detection and version detection
matomo-org/device-detector pull request #6522
Opened 2020-12-13 22:55 UTC by liviuconcioiu

2020-12-14 07:58 UTC, sanchezzzhak commented
https://en.wikipedia.org/wiki/Darwin_(operating_system)#Release_history
we can detectiob ios version by Darwin

2020-12-14 08:03 UTC, sanchezzzhak commented on Tests/Parser/fixtures/oss.yml
> +    version: "10.11"
10.11.6

2020-12-14 08:11 UTC, sanchezzzhak approved these changes, later dismissed

2020-12-14 14:48 UTC, liviuconcioiu commented
Yes, I will do them later today.

2020-12-16 12:37 UTC, liviuconcioiu commented
@sanchezzzhak can you please check those changes when you have time? If there are okay, I'll make changes for the other versions and for Mac too.

2020-12-16 13:19 UTC, sanchezzzhak requested changes

2020-12-16 13:19 UTC, sanchezzzhak commented on Tests/Parser/fixtures/oss.yml
> +    version: "13"
version: "13.0"

2020-12-16 13:19 UTC, sanchezzzhak commented on Tests/Parser/fixtures/oss.yml
> +    version: "14"
version: "14.0"

2020-12-16 13:19 UTC, sanchezzzhak commented on regexes/oss.yml
> +- regex: 'CFNetwork/1206.*Darwin/20.1.0(?!.*x86_64)'
cfnetwork version is no needed, change to
'CFNetwork/.+ Darwin/20.1.0(?!.*x86_64)'

2020-12-16 13:19 UTC, sanchezzzhak commented on regexes/oss.yml
> +  version: '14'
version: '14.0'

2020-12-16 13:19 UTC, sanchezzzhak commented on regexes/oss.yml
> +  version: '11.4'
replace  CFNetwork/* version if  definition goes by  darwin version
Example
```
CFNetwork/.+ Darwin/17.6.0(?!.*x86_64)
```

2020-12-16 13:24 UTC, sanchezzzhak commented
add detect version `Safari/15610.2.11.51.10 CFNetwork/1209 Darwin/20.2.0`
macOS 11.1 
iOS 14.3

2020-12-16 14:21 UTC, sanchezzzhak approved these changes, later dismissed

2020-12-16 15:01 UTC, sanchezzzhak submitted a review, later dismissed

2020-12-16 15:35 UTC, liviuconcioiu commented
I've found https://www.tonymacx86.com/ to be a more reliable source than Wikipedia. It has all versions.

`"macOS 10.12.6 Update" site:tonymacx86.com`
https://www.tonymacx86.com/threads/macos-10-12-6-update.224836/

2020-12-28 07:08 UTC, sanchezzzhak approved these changes

2020-12-29 23:51 UTC, sgiehl approved these changes

2020-12-29 23:52 UTC, merged

2021-01-14 20:59 UTC, adityapatadia commented
Which version will have this capability?

2021-01-14 21:57 UTC, sanchezzzhak commented
> Which version will have this capability?

available in the latest release 4.1

2021-01-22 20:13 UTC, adityapatadia commented
When I add this user-agent, it does not detect the app name and version: `Clovia/3.3.1 CFNetwork/1206 Darwin/20.1.0`. We were expecting it to detect Clovia as client app with 3.3.1 version.