Adds detection for Whale OS
matomo-org/device-detector pull request #6559
Opened 2020-12-30 22:07 UTC by liviuconcioiu

2021-01-01 17:44 UTC, sanchezzzhak requested changes, later dismissed

2021-01-01 17:44 UTC, sanchezzzhak commented on Parser/OperatingSystem.php
> +            'ORD', 'TOS', 'RSO', 'DEE', 'FRE', 'WHS',
multiplatform Linux & Android  https://partner.zeasn.com/partnerportal/DeviceMapping/index.jhtml 
I think we should create a new OS family
```php
'Other Smart TV' => [
     'WHS'
]
```

2021-01-04 10:49 UTC, sgiehl submitted a review, later dismissed

2021-01-04 10:51 UTC, sgiehl approved these changes

2021-01-04 11:03 UTC, merged