Adds detection for various mobile apps
matomo-org/device-detector pull request #6623
Opened 2021-02-05 18:32 UTC by liviuconcioiu

2021-02-07 03:42 UTC, liviuconcioiu commented
I think I should write a regex rule for each Microsoft Office app, since in README.md, is seen as
`Microsoft Office $1`
[https://github.com/matomo-org/device-detector#list-of-detected-mobile-apps](https://github.com/matomo-org/device-detector#list-of-detected-mobile-apps)

2021-02-07 08:39 UTC, sanchezzzhak submitted a review, later dismissed

2021-02-18 15:38 UTC, sanchezzzhak requested changes

2021-02-18 15:38 UTC, sanchezzzhak commented on regexes/client/mobile_apps.yml
> +  name: 'Google'
I installed the application by the link, the useragent there is like this
'Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_8 as Mac OS X) AppleWebKit/605.1.15 (KHTML as Gecko) GSA/137.2.345735309 Mobile/16G201 Safari/604.1`

set name `Google Search App`

2021-02-18 20:39 UTC, sanchezzzhak commented on regexes/client/mobile_apps.yml
> +- regex: '(?:com.google.GoogleMobile|GSA)/([\d\.]+)?'
note:
the maximum version I could find in the logs is dated 2019.02
`google. com. Google Mobile/67.1.0 for iPhone/12.1.3 for iPhone7_2`

if compare version 67 with the release date 2019.02.16 and take useragent from the log 2019.02 -  then everything fits together

Website https://iphone.apkpure.com/google/com.google.googlemobile there I looked at the app versions ( appstore is limited to the list of versions)

2021-02-18 20:40 UTC, sanchezzzhak approved these changes

2021-02-18 20:41 UTC, merged