Improves detection for Samsung
matomo-org/device-detector pull request #6639
Opened 2021-02-10 03:25 UTC by liviuconcioiu

2021-02-10 03:30 UTC, liviuconcioiu commented
Please don't merge this PR because I want to add a few more commits. Also, I've noticed multiple rules like `SM-G988(?:0BNQUW]|U1)`. `U1` must be placed before `[0BNQUW]`. Should I correct those rules?

2021-02-10 21:19 UTC, sanchezzzhak requested changes

2021-02-10 21:19 UTC, sanchezzzhak commented on Tests/fixtures/phablet.yml
> +    type: phablet
type: tablet
size screen: 7.0
https://whatismyphone.com/vendors/samsung/galaxy-tabq-sm-t2519
https://www.devicespecifications.com/en/model/bf5d2e36

2021-02-11 19:29 UTC, sanchezzzhak commented on Tests/fixtures/phablet.yml
> +  user_agent: Mozilla/5.0 (Linux; Android 10; SM-F9160) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36
this is a duplicate of the test, the above is exactly the same test

2021-02-11 23:32 UTC, liviuconcioiu commented
@sanchezzzhak I've seen models written as `Galaxy Tab S7+ 12.4" 5G`. Shouldn't this be written as `Galaxy Tab S7+ 5G 12.4"` instead? The same goes for `Galaxy Tab S6 10.4" Lite WiFi`, which should be `Galaxy Tab S6 Lite WiFi 10.4"`.

2021-02-12 07:21 UTC, sanchezzzhak commented
@liviuconcioiu It's hard to say.

Most Samsung table models are named in this format 

tablet  - 
`model name` +  `(screen size)` +  `(year)`  + `network type (3G|4G|5G|WiFi|LTE)`

I think it would be better to leave it as it is
pass `Galaxy Tab S7+ 12.4" 5G`
rename `Galaxy Tab S6 10.4" Lite WiFi` in `Galaxy Tab S6 Lite 10.4" WiFi`

2021-02-12 12:24 UTC, liviuconcioiu commented
If so, then `Galaxy Tab A 8.0" LTE (2018)` should be changed to `Galaxy Tab A 8.0" (2018) LTE` right?

2021-02-15 12:57 UTC, sanchezzzhak commented on Tests/fixtures/tablet-1.yml
> +    model: Galaxy Tab Active 2 8.0"
`Galaxy Tab Active 2 8.0" WiFi`

https://www.samsung.com/sg/business/tablets/galaxy-tab-active-2-8-0-t390/sm-t390nzkaxsp/

2021-02-15 13:43 UTC, sanchezzzhak commented on Tests/fixtures/smartphone-2.yml
> +    model: Galaxy Feel
`Galaxy Feel 2`

2021-02-15 13:46 UTC, sanchezzzhak commented on Tests/fixtures/smartphone-2.yml
> +    model: Galaxy S20
`Galaxy S20 5G`

2021-02-15 14:05 UTC, sanchezzzhak approved these changes

2021-02-15 20:23 UTC, merged