Adds detection for Qwant Mobile iOS browser
matomo-org/device-detector pull request #6641
Opened 2021-02-13 02:30 UTC by liviuconcioiu

2021-02-15 14:19 UTC, sanchezzzhak commented
@sgiehl Is it acceptable to split the browser into two names? 
Similar precedent: `Opera Mini iOS`, `Firefox Mobile iOS`

2021-02-23 08:59 UTC, sgiehl commented
@sanchezzzhak  sorry for the delay. Good question. I guess I actually would say no. We should detect that as one, to keep it simple. There is actually no benefit in splitting it. We maybe should even consider removing the other iOS browser versions. Or do you have another opinion on that?

2021-02-23 13:07 UTC, sanchezzzhak commented
I am in favor of not specifying prefixes

2021-02-23 13:09 UTC, sanchezzzhak requested changes

2021-02-23 13:09 UTC, sanchezzzhak commented on regexes/client/browsers.yml
> +  name: 'Qwant Mobile iOS'
change name: `Qwant Mobile`

2021-02-23 13:30 UTC, sanchezzzhak approved these changes

2021-02-23 13:30 UTC, merged