Detect devices for existing brands: Homtom, Huawei, Tecno Mobile, LG, LT Mobile, Prestigio, Blackview, OPPO, Tone, Vivo, SFR, Philips, Archos
matomo-org/device-detector pull request #6779
Opened 2021-06-20 11:16 UTC by sanchezzzhak

2021-06-22 14:31 UTC, sgiehl submitted a review, later dismissed

2021-07-06 09:06 UTC, sgiehl requested changes

2021-07-06 09:24 UTC, sanchezzzhak commented on regexes/device/mobiles.yml
> +  regex: 'Homtom|(?:HT[0-9]{1,2}(?: ?Pro)?|HT50)(?:[);/ ]|$)'
fixed

2021-07-06 09:30 UTC, sgiehl approved these changes

2021-07-06 09:33 UTC, merged