Fix regexes for Ruby
matomo-org/device-detector pull request #6992
Opened 2022-02-10 18:05 UTC by sanchezzzhak

#6991

2022-02-14 15:25 UTC, sgiehl requested changes
Left some comments, where the changes actually were not what I would have expected.

2022-02-14 15:25 UTC, sgiehl commented on regexes/client/browsers.yml
> +- regex: 'WAP Browser/MAUI|(?:.*_)?Maui Wap Browser|MAUI[- ]Browser'
Doesn't that actually change the regex? Wouldn't that change be needed to keep that same behaviour?
```suggestion
- regex: 'WAP Browser/MAUI|(?:\w*)Maui Wap Browser|MAUI[- ]Browser'
```

2022-02-14 15:25 UTC, sgiehl commented on regexes/device/mobiles.yml
> +  regex: 'MAXVI[ _](?:MS401)(?:[);/ ]|$)|.*_?MAXVI?_\w|MS502[_ ]Orion|MS531'
That doesn't seem to be the same as before either:
```suggestion
  regex: 'MAXVI[ _](?:MS401)(?:[);/ ]|$)|\w*_?MAXVI?_\w+|MS502[_ ]Orion|MS531'
```

2022-02-14 15:25 UTC, sgiehl commented on regexes/device/mobiles.yml
> +    - regex: '.*_?MAXVI_(P11|K10|X[358]00)_'
```suggestion
    - regex: '\w*MAXVI_(P11|K10|X[358]00)_'
```

2022-02-14 15:25 UTC, sgiehl commented on regexes/oss.yml
> +- regex: '[ ]([\d\.]+)[)] AppleWebKit.*ROBLOX Android App'
Didn't the escaping work for ruby?

2022-02-15 14:22 UTC, sgiehl approved these changes

2022-02-15 14:26 UTC, merged

2022-02-17 13:16 UTC, jrochkind commented
thank you! --a rubyist