Adds detection for Foresight Linux, Kanotix, LindowsOS, Linspire, moonOS, Pardus, Zenwalk GNU Linux operating systems
matomo-org/device-detector pull request #7011
Opened 2022-02-22 05:04 UTC by liviuconcioiu

2022-02-22 05:09 UTC, liviuconcioiu commented
Anyone knows why lately workflows need approval? I'm not a first time contributor.

![Untitled](https://user-images.githubusercontent.com/25424343/155066885-d6aeb4c8-65e5-4665-8145-a0ec299d44b2.png)

2022-02-22 08:36 UTC, sgiehl commented
@liviuconcioiu seems the action settings had been changed and an approval was always required for all external contributors. I've changed it again. Guess it should work as before again.

2022-02-23 15:34 UTC, sanchezzzhak requested changes

2022-02-23 15:40 UTC, sanchezzzhak approved these changes

2022-02-23 15:40 UTC, merged