Implement Blink version detection via Chrome/ token.
matomo-org/device-detector pull request #7063
Opened 2022-03-22 03:23 UTC by JBYoshi

### Description:

The engine version parser looks for a token that specifically matches the engine name by default. However, Blink-based browsers don't mention "Blink" in the user agent; they almost always mention Chrome instead, and they include the engine version under that. Because of that confusion, none of the Blink browsers include engine versions (except for Chrome Mobile on the "Andi 5G Blink 4G" smartphone, which incorrectly returns the 4). This PR adds an override in the engine version parser to look for the Chrome/ token instead.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-03-22 09:27 UTC, sanchezzzhak requested changes

2022-03-22 09:27 UTC, sanchezzzhak commented on Parser/Client/Browser.php
> +                $engineVersion = self::buildEngineVersion($engine);
replace to 
```php
$engineVersion = $this->buildEngineVersion($engine);
```

2022-03-22 09:51 UTC, sanchezzzhak commented
it really case that chrome version = blink version (except for iOS and iPadOS)
https://en.wikipedia.org/wiki/Google_Chrome_version_history

2022-03-23 06:19 UTC, sanchezzzhak approved these changes

2022-03-23 12:42 UTC, merged

2024-01-25 21:39 UTC, mindreader commented
@JBYoshi I tagged a new updated version a few minutes ago.

As for your private fork, I understand the need to do hacky business things sometimes, but I would appreciate if you have made any performance enhancements that you consider contributing back. Maintaining and constantly updating from upstream is not really something you want to do all by yourself every few months as our code bases diverge over time.