Detect devices for existing brands and Detect Pi Browser
matomo-org/device-detector pull request #7131
Opened 2022-05-28 15:55 UTC by sanchezzzhak

2022-05-29 11:06 UTC, liviuconcioiu requested changes
@sanchezzzhak can you add Pi Browser to client hints too? Ans also, a link for the browser https://play.google.com/store/apps/details?id=pi.browser

`'pi.browser': 'Pi Browser'`

2022-05-29 11:45 UTC, liviuconcioiu submitted a review, later dismissed

2022-05-30 14:47 UTC, sgiehl commented
@sanchezzzhak would you mind resolving the conflicts?

2022-05-31 11:45 UTC, sgiehl approved these changes

2022-05-31 11:45 UTC, merged