Detect new brands: Cidea, Cuiud, Daria,  HiBy, mipo and Detect devices for exist brands
matomo-org/device-detector pull request #7671
Opened 2024-04-27 18:28 UTC by sanchezzzhak

2024-04-27 23:28 UTC, liviuconcioiu requested changes

2024-04-27 23:28 UTC, liviuconcioiu commented on regexes/device/mobiles.yml
> +  model: '$1'
```suggestion
  device: 'smartphone'
  model: '$1'
```

2024-04-28 05:47 UTC, Simbiat commented on Parser/Device/AbstractDeviceParser.php
> +        'CIA' => 'Cidea',
Based on photos I've found (for example https://jiji.ng/surulere/tablets/new-c-idea-cm7000-plus-512-gb-rsYzAEHJMsdZor3u7ZfnlZks.html) it should be `C Idea`

2024-05-02 11:48 UTC, liviuconcioiu approved these changes

2024-05-02 13:19 UTC, merged